//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoppingStore_2108G1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Details
    {
        public string Order_Code { get; set; }
        public Nullable<int> Order_ID { get; set; }
        public Nullable<int> Product_id { get; set; }
        public Nullable<int> Qty { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
